name: Python Package using Conda

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file env.yml --name base
    - name: Install library
      run: |
        pip install .
    - name: Lint with flake8
      run: |
        $CONDA/bin/conda install flake8
        $CONDA/bin/flake8 . --count --max-line-length=140 --exclude=srcdoc --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest
    - name: Sphinx build
      uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: "srcdoc/"
