name: Sphinx publish


on: 
  release:
    types: [created]

  push:
    branches:
      - documentation


jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file env.yml --name base
    - name: Install library
      run: |
        pip install .
    - name: Install sphinx
      run: |
        $CONDA/bin/conda install -c anaconda sphinx
        $CONDA/bin/conda install -c anaconda sphinx_rtd_theme
    - name: Move to source directory
      run: cd srcdoc/
    - name: Sphinx build
      run: |
        make html
      # uses: ammaraskar/sphinx-action@0.4
      # with:
      #   docs-folder: "srcdoc/"
    - name: git config
      run: |
        git config --local user.email secrets.email
        git config --local user.name secrets.name
    - name: Check for changes
      run: git status
    - name: Stage changed files in docs
      run: git add docs
    - name: Commit docs
      run: git commit -m "Auto update documentation"
    - name: Push docs to main
      run: git push origin HEAD:documentation
    
        
